links:
  shop: 'https://antecedentium-store.tebex.io/'
  discord: 'https://discord.gg/acvqsKDQkV'

command-config:
  stop-command:
    min5: '&c&lBROADCAST  &eRestarting main server in 5 minutes.'
    min4: '&c&lBROADCAST  &eRestarting main server in 4 minutes.'
    min3: '&c&lBROADCAST  &eRestarting main server in 3 minutes.'
    min2: '&c&lBROADCAST  &eRestarting main server in 2 minutes.'
    min1: '&c&lBROADCAST  &eRestarting main server in 1 minute.'
    now: '&c&lBROADCAST  &eRestarting main server NOW!'

modules:
  donkey-dupe:
    enabled: true
    messages:
      dupe-disabled: '&cDonkey dupe is disabled, use SalDupe.'
  god-mode:
    enabled: true
    messages:
      god-mode-disabled: '&cGod mode exploit is disabled sorry.'
  end-gateway-crash:
    enabled: true
    messages:
      disabled: '&cGoing through an end gateway while riding an entity/minecart is disabled.'
  tab:
    enabled: true
    config:
      info:
        - "Updated AntecedentiumUtil plugin and added custom tab"
        - "to the server."
      footer:
        contact: "terroristswin777@gmail.com"
        discussion: "https://discord.gg/9j2bdwyADp"
        store: "https://antecedentium-store.tebex.io/"
      updated-every: 1
  anti-illegals:
    enabled: true
    mode: NORMAL # LOW/NORMAL/STRICT/HYPIXEL
  anti-spawnhome:
    enabled: true
    blocks: 800
    messages:
      spawn-message: '&cYou are too close to spawn, you need to be &l%blocks% blocks &caway from spawn to use /home.'
      vehicle-message: "&cYou can't use /home while inside a vehicle!"
  recipe-lag:
    enabled: true
  chest-lag:
    enabled: true
    config:
      max-spam: 16
      books-delete: true
    messages:
      kick: '&cHello'

messages:
  suicide-message: '&cYou commited suicide'