links:
  shop: 'https://antecedentium-store.tebex.io/'
  discord: 'https://discord.gg/XVprA5BFCF'

command-config:
  stop-command:
    min5: '&e[SERVER] Server restarting in 5 minutes...'
    min4: '&e[SERVER] Server restarting in 4 minutes...'
    min3: '&e[SERVER] Server restarting in 3 minutes...'
    min2: '&e[SERVER] Server restarting in 2 minutes...'
    min1: '&e[SERVER] Server restarting in 1 minute...'
    now: '&e[SERVER] Server restarting NOW...'
  help-command:
    - "&e/help &r- Help command."
    - "&e/buy &r- Shows the shop url."
    - "&e/discord &r- Shows the discord url."
    - "&e/stats &r- Shows some info about the server."
    - "&e/joindate <player> &r- Shows the exact join date of a player."
    - "&e/kill &r- Suicide."
    - "&e/w <player> <message> &r- Whisper someone."
    - "&e/r <message> &r- Reply to the last one who talked with you."
    - "&e/ignore <player> &r- Ignore whispers and messages from a player."
    - "&e/home <home> &r- Teleports you to your home called \"home\"."
    - "&e/sethome <name> &r- Sets a home with a name."

modules:
  donkey-dupe:
    enabled: true
    messages:
      dupe-disabled: '&cDonkey dupe is disabled, use SalDupe.'
  god-mode:
    enabled: true
    messages:
      god-mode-disabled: '&cGod mode exploit is disabled sorry.'
  end-gateway-crash:
    enabled: true
    messages:
      disabled: '&cGoing through an end gateway while riding an entity/minecart is disabled.'
  tab:
    enabled: true
    config:
      name: 'antecedentium'
      colored-name: '&6Antece&edentium'
      info:
        - New death messages
        - Optimized the server a bit
      footer:
        contact: 'terroristswin777@gmail.com'
        discussion: 'https://discord.gg/XVprA5BFCF'
        store: 'https://antecedentium-store.tebex.io/'
      updated-every: 5
  anti-illegals:
    enabled: false
    mode: NONE
  anti-spawnhome:
    enabled: true
    blocks: 800
    messages:
      spawn-message: '&cYou are too close to spawn, you need to be &l%blocks% blocks &caway from spawn to use /home.'
      vehicle-message: "&cYou can't use /home while inside a vehicle!"
  recipe-lag:
    enabled: true
  chest-lag:
    enabled: true
    config:
      max-spam: 16
      books-delete: true
    messages:
      kick: '&cHello'
  light-lag:
    enabled: true
    config:
      max-spam: 12
      crash: false
    messages:
      kick: '&cHello'
  chunk-ban:
    enabled: true
    config:
      tile-entity-max: 512
      skull-max: 100
    messages:
      prevent: '&6Chunkbanning is not allowed'
  32k-damage:
    enabled: true
    config:
      apply-sword: true
  nether-roof:
    enabled: true
    config:
      level: 127
      damage: 10.0
  lag-prevention:
    enabled: true
    modules:
      elytra:
        enabled: true
        config:
          tps: 15.0
          overworld: true
          nether: false
          end: false
      physics:
        enabled: true
        config:
          tps: 10.0
      redstone:
        enabled: true
        config:
          tps: 14.0
  redstone-limit:
    enabled: true
    config:
      max-redstone: 16

messages:
  suicide-message: 'rip'